import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    visualDensity: const VisualDensity(vertical: 0.5, horizontal: 0.5),
    primarySwatch: const MaterialColor(
      0xFF000000,
      <int, Color>{
        50: Color(0xa1838383),
        100: Color(0xa1838181),
        200: Color(0xa1858585),
        300: Color(0xa1181818),
        400: Color(0xff181818),
        500: Color(0xffa6a6a6),
        600: Color(0xffa9a9a9),
        700: Color(0xff565656),
        800: Color(0xff363636),
        900: Color(0xff262626)
      },
    ),
    primaryColor: const Color(0xff5D4524),
    primaryColorBrightness: Brightness.dark,
    primaryColorLight: const Color(0x1a311F06),
    primaryColorDark: const Color(0xff838383),
    canvasColor: const Color(0xff000000),
    scaffoldBackgroundColor: const Color(0xffB5BFD3),
    bottomAppBarColor: const Color(0xff838383),
    cardColor: const Color(0xaa311F06),
    dividerColor: const Color(0x1f838383),
    focusColor: const Color(0x1a311F06),
    hoverColor: const Color(0xa15D4524),
    highlightColor: const Color(0xaf2F1E06),
    splashColor: const Color(0xfff2f2f2),
    selectedRowColor: Colors.grey,
    unselectedWidgetColor: Colors.grey.shade400,
    disabledColor: Colors.grey.shade200,
    buttonTheme: const ButtonThemeData(),
    toggleButtonsTheme: const ToggleButtonsThemeData(),
    secondaryHeaderColor: Colors.grey,
    backgroundColor: const Color(0xffa0a0a0),
    dialogBackgroundColor: Colors.white,
    indicatorColor:  Colors.yellow,
    hintColor: Colors.grey,
    errorColor: Colors.red,
    toggleableActiveColor: Colors.yellow,
    textTheme: const TextTheme(),
    primaryTextTheme: const TextTheme(),
    inputDecorationTheme: const InputDecorationTheme(),
    iconTheme: const IconThemeData(),
    primaryIconTheme: const IconThemeData(),
    sliderTheme: const SliderThemeData(),
    tabBarTheme: const TabBarTheme(),
    tooltipTheme: const TooltipThemeData(),
    cardTheme: const CardTheme(),
    chipTheme: const ChipThemeData(
        backgroundColor: Color(0xff2F1E06),
        disabledColor: Color(0xa15D4524),
        shape: StadiumBorder(),
        brightness: Brightness.dark,
        labelPadding: EdgeInsets.all(8),
        labelStyle: TextStyle(),
        padding: EdgeInsets.all(8),
        secondaryLabelStyle: TextStyle(),
        secondarySelectedColor: Colors.white38,
        selectedColor: Colors.white
        // chip theme
        ),
    platform: TargetPlatform.android,
    materialTapTargetSize: MaterialTapTargetSize.padded,
    applyElevationOverlayColor: true,
    pageTransitionsTheme: const PageTransitionsTheme(),
    appBarTheme: const AppBarTheme(),
    bottomAppBarTheme: const BottomAppBarTheme(),
    colorScheme: const ColorScheme(
        primary: Color(0xffffffff),
        primaryVariant: Color(0x1a311F06),
        secondary: Color(0xffffffff),
        secondaryVariant: Color(0xaa457BE0),
        brightness: Brightness.dark,
        background: Color(0xffB5BFD3),
        error: Colors.red,
        onBackground: Color(0xffB5BFD3),
        onError: Colors.red,
        onPrimary: Color(0xff515151),
        onSecondary: Color(0xffffffff),
        onSurface: Color(0xffffffff),
        surface: Color(0xffffffff)),
    snackBarTheme: const SnackBarThemeData(
        ),
    dialogTheme: const DialogTheme(),
    floatingActionButtonTheme: const FloatingActionButtonThemeData(),
    navigationRailTheme: const NavigationRailThemeData(),
    cupertinoOverrideTheme: const CupertinoThemeData(),
    bottomSheetTheme: const BottomSheetThemeData(),
    popupMenuTheme: const PopupMenuThemeData(),
    bannerTheme: const MaterialBannerThemeData(),
    dividerTheme: const DividerThemeData(),
    buttonBarTheme: const ButtonBarThemeData(),
    fontFamily: 'ROBOTO',
    splashFactory: InkSplash.splashFactory);
